Create/Update Progress-bar config
tiagomatosweb/tw-vue pull request #20
Opened 2022-02-06 02:26 UTC by vuedavi

**Alterações:** 

- Componente Progress-bar criado
- Pagina de documentação da Progress-bar criada
- Arquivos de rota, navegação e configução do componente fora alterados e criados

2022-02-06 23:19 UTC, tiagomatosweb requested changes

2022-02-06 23:30 UTC, vuedavi commented on src/components/progressbar/ProgressBar.vue
> +        <div v-show="activeToolTip == true" v-bind:class="getToolTipClass">
activeToolTip  == alterado para apenas activeToolTip

2022-02-06 23:33 UTC, vuedavi commented on src/components/progressbar/ProgressBar.vue
> +            type: String,
Alterado para "[String, Number]"

2022-02-06 23:35 UTC, vuedavi reviewed
Todas as alterções necessárias foram feitas!

2022-02-07 06:49 UTC, tiagomatosweb approved these changes

2022-02-07 06:50 UTC, merged